#include "codegen.hpp"
#include <string>

namespace bf {

/**
 * Our assembly generation logic. We use NASM Intel syntax because it's
 * clean and matches our mental model of the CPU's registers.
 * 
 * Register usage:
 * - rbx: Our tape pointer (points into the 'tape' buffer)
 * - al: Used for temporary 8-bit math
 * - rax, rdi, rsi, rdx: Used for Linux syscalls
 */
void CodeGen::generate_nasm(const ActionPlan& plan, std::ostream& out) {
    // Standard NASM boilerplate
    out << "; Generated by the 'Compiler from Scratch' Project\n";
    out << "section .bss\n";
    out << "    tape resb 30000\n\n"; // Standard 30k cell tape
    out << "section .text\n";
    out << "    global _start\n\n";
    out << "_start:\n";
    out << "    mov rbx, tape\n\n";

    for (size_t i = 0; i < plan.size(); ++i) {
        const auto& act = plan[i];
        switch (act.type) {
            case ActionType::MovePointer:
                out << "    add rbx, " << act.amount << " ; move pointer\n";
                break;

            case ActionType::ChangeValue: {
                std::string target = "[rbx";
                if (act.relative_offset != 0) {
                    target += (act.relative_offset > 0 ? " + " : " - ");
                    target += std::to_string(std::abs(act.relative_offset));
                }
                target += "]";

                if (act.amount == 1) {
                    out << "    inc byte " << target << "\n";
                } else if (act.amount == -1) {
                    out << "    dec byte " << target << "\n";
                } else if (act.amount != 0) {
                    out << "    add byte " << target << ", " << act.amount << "\n";
                }
                break;
            }

            case ActionType::Speak:
                out << "    ; write char to stdout\n";
                out << "    mov rax, 1\n"; // sys_write
                out << "    mov rdi, 1\n"; // stdout
                out << "    mov rsi, rbx\n";
                out << "    mov rdx, 1\n";
                out << "    syscall\n";
                break;

            case ActionType::Listen:
                out << "    ; read char from stdin\n";
                out << "    mov rax, 0\n"; // sys_read
                out << "    mov rdi, 0\n"; // stdin
                out << "    mov rsi, rbx\n";
                out << "    mov rdx, 1\n";
                out << "    syscall\n";
                break;

            case ActionType::BeginLoop:
                out << "label_" << i << ":\n";
                out << "    cmp byte [rbx], 0\n";
                out << "    je label_" << act.jump_target << "\n";
                break;

            case ActionType::EndLoop:
                out << "label_" << i << ":\n";
                out << "    cmp byte [rbx], 0\n";
                out << "    jne label_" << act.jump_target << "\n";
                break;

            case ActionType::ResetToZero:
                out << "    mov byte [rbx], 0 ; reset current cell\n";
                break;

            case ActionType::MultiplyAndAdd:
                out << "    ; optimized multiplication\n";
                out << "    mov al, byte [rbx]\n";
                if (act.amount == 1) {
                    out << "    add byte [rbx + " << act.relative_offset << "], al\n";
                } else if (act.amount == -1) {
                    out << "    sub byte [rbx + " << act.relative_offset << "], al\n";
                } else {
                    out << "    mov dl, " << (int)(uint8_t)act.amount << "\n";
                    out << "    imul dl\n";
                    out << "    add byte [rbx + " << act.relative_offset << "], al\n";
                }
                break;

            case ActionType::SeekZero:
                out << "    ; optimized scan\n";
                out << "    cmp byte [rbx], 0\n";
                out << "    je scan_end_" << i << "\n";
                out << "scan_loop_" << i << ":\n";
                out << "    add rbx, " << act.amount << "\n";
                out << "    cmp byte [rbx], 0\n";
                out << "    jne scan_loop_" << i << "\n";
                out << "scan_end_" << i << ":\n";
                break;
        }
    }

    // Exit gracefully
    out << "\n    ; exit(0)\n";
    out << "    mov rax, 60\n"; // sys_exit
    out << "    xor rdi, rdi\n";
    out << "    syscall\n";
}

} // namespace bf
